### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by hopesala** [Jakaria08/EESRGAN#11]
I download the file DetectionPatches_256x256,and then generate the HR / LR directory using file scripts_GAN_HR-LR.py
and the HR / LR directory are generated as expected,
however when I run the python train.py -c config_GAN.json command after modify the config_GAN.json"data_dir_GT": "/media/cao/WINDOWS/Users/123/Downloads/DetectionPatches_256x256/Potsdam_ISPRS/HR/x4/",
            "data_dir_LQ": "/media/cao/WINDOWS/Users/123/Downloads/DetectionPatches_256x256/Potsdam_ISPRS/LR/x4/",
"FRCNN_model": "/media/cao/WINDOWS/Users/123/Downloads/EESRGAN-master/saved/FRCNN_model_LR_LR_cowc/",
        "pretrain_model_G": "/media/cao/WINDOWS/Users/123/Downloads/EESRGAN-master/saved/pretrained_models_EESRGAN_FRCNN/170000_G.pth",
        "pretrain_model_D": "/media/cao/WINDOWS/Users/123/Downloads/EESRGAN-master/saved/pretrained_models_EESRGAN_FRCNN/170000_D.pth",
        "pretrain_model_FRCNN": "/media/cao/WINDOWS/Users/123/Downloads/EESRGAN-master/saved/pretrained_models_EESRGAN_FRCNN/170000_FRCNN.pth",
        "pretrain_model_FRCNN_LR_LR": "/media/cao/WINDOWS/Users/123/Downloads/EESRGAN-master/saved/FRCNN_model_LR_LR_cowc/0_FRCNN_LR_LR.pth",

I still got the error :ValueError: num_samples should be a positive integer value, but got num_samples=0

Is there somewhere I forget to do or something is wrong?
my Chinese English(Chinalish) is poor, thanks you very much

**Comment by Jakaria08** [comment]
It seems like the program is not getting the correct directory. Make sure to include the complete path of the directory. You can print the path here to make sure your path is correct: https://github.com/Jakaria08/EESRGAN/blob/c646296f68c1158c62e6bf9eca5fc82103e4f120/scripts_for_datasets/COWC_EESRGAN_FRCNN_dataset.py#L18

**Comment by hopesala** [comment]
thanks, the problem is solved, it is the path problem, I passed in the wrong path in the train.py: valid_data_loader = module_data.COWCGANFrcnnDataLoader

**Comment by shazaizai** [comment]
"pretrain_model_FRCNN_LR_LR": "/media/cao/WINDOWS/Users/123/Downloads/EESRGAN-master/saved/FRCNN_model_LR_LR_cowc/0_FRCNN_LR_LR.pth",where should i download？
