### ISSUE TITLE
Can we train to only get Super-Res images?

### ISSUE THREAD

**Issue by purijs** [Jakaria08/EESRGAN#15]
Hi

I'm trying to make this work on my custom dataset, I only have jpegs but no annotation data and am only interested getting the SR images as output. Will the code work without annotations, where all can I modify the code?

**Comment by Jakaria08** [comment]
There are many hardcoded parts in my code; sorry for that. Many parts are needed to be changed. Try to run this project: https://github.com/kuihua/EEGAN, it works only with superresolution.

For my project, you should use this model: https://github.com/Jakaria08/EESRGAN/blob/c646296f68c1158c62e6bf9eca5fc82103e4f120/model/ESRGAN_EESN_Model.py#L132
The dataset script also needed to be changed. Besides these you need to change some other code segments that are dependent.
