### ISSUE TITLE
about the datasets

### ISSUE THREAD

**Issue by cl886699** [Jakaria08/EESRGAN#19]
I tested your pretrained model. I got high score on Potsdam, but low score on Toronto.
How dit you select the dataset
Did you just train on Potsdam?

Potsdam
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.982
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.990
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.990
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.982
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.985
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.229
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.937
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.993
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.993
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.994
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

Toronto
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.235
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.388
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.261
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.246
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.256
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.106
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.270
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.275
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.275
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.280
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

**Comment by Jakaria08** [comment]
The model that I have uploaded might be trained on Potsdam only (I have several models: trained on the images from separate cities and trained on all data from different cities). I have to recheck the models that I trained. I have a final model trained on the images from different cities, and I will upload if I find it. Thank you for the question.

**Comment by sagaragarwal2404** [comment]
> I tested your pretrained model. I got high score on Potsdam, but low score on Toronto.
> How dit you select the dataset
> Did you just train on Potsdam?
> 
> Potsdam
> IoU metric: bbox
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.982
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.990
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.990
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.982
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.985
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.229
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.937
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.993
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.993
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.994
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> 
> Toronto
> IoU metric: bbox
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.235
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.388
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.261
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.246
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.256
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.106
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.270
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.275
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.275
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.280
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

bro I want your help implementing this code.if you could help

**Comment by Frost-Mactavish** [comment]
请问你是怎么训练的？我这里很容易就训练跑飞了
