### ISSUE TITLE
How to change another detector network

### ISSUE THREAD

**Issue by JJY0710** [Jakaria08/EESRGAN#20]
I want to change the FRCNN_model to another model, such as Casecade RCNN or other detection models trained by me.How can I do. Thank you.

**Comment by Jakaria08** [comment]
In the following segment, I used FRCNN. You can add your own model here: https://github.com/Jakaria08/EESRGAN/blob/c646296f68c1158c62e6bf9eca5fc82103e4f120/model/ESRGAN_EESN_FRCNN_Model.py#L40

**Comment by JJY0710** [comment]
> In the following segment, I used FRCNN. You can add your own model here:
> 
> https://github.com/Jakaria08/EESRGAN/blob/c646296f68c1158c62e6bf9eca5fc82103e4f120/model/ESRGAN_EESN_FRCNN_Model.py#L40

OK, thank you very much
