### ISSUE TITLE
cowc 

### ISSUE THREAD

**Issue by hhakko** [Jakaria08/EESRGAN#4]
Can you upload the COWC dataset for the experiment

**Comment by Jakaria08** [comment]
Hello,
Download dataset from here: https://gdo152.llnl.gov/cowc/download/cowc-m/datasets/
Here is a GitHub repo to create your own image patches: https://github.com/LLNL/cowc/tree/master/COWC-M 
You can also download pre-made dataset: https://gdo152.llnl.gov/cowc/download/cowc-m/datasets/DetectionPatches_256x256.tgz and use the  following script to create high/low-resolution and bicubic images: https://github.com/Jakaria08/EESRGAN/blob/1f93130d8e99166e7bc4d1640329450feec9ff9c/scripts_for_datasets/scripts_GAN_HR-LR.py#L24 
Thanks

**Comment by Jakaria08** [comment]
The pre-made dataset has overlapping image patches, which means one car may appear in two different image patches. If you only test, that should be no problem, but if you train and test, then be careful when you create the test dataset.
