### ISSUE TITLE
HR/X4  LR/X4

### ISSUE THREAD

**Issue by hhakko** [Jakaria08/EESRGAN#6]
For the data set aspect in this paper, I want to consult you a question. I have seen your code. The data input is LR and HR . LR  is generated by sampling under the COWC data set. HR  is the original image of CoWC. When testing, the input is generated by sampling under the COWC data set. Shouldn't the image we tested be the original CoWC image? If I want to use other data sets, how to set the training input? The test input should be the original test set map of the data set? Isn't the original intention of our algorithm  small object dataset?
This question bothers me very much. I look forward to your reply,Thank you

**Comment by Jakaria08** [comment]
For input, we need only low-resolution images: 4x downsampled with 64*64 tile size for the COWC dataset. Then we get super-resolved images with detection.

For testing a new satellite dataset with a resolution around 0.6 m to 1 m, you should create 64*64 tiles for our architecture. You can also use larger tiles but in that case, you have to change the internal architecture of the discriminator to handle the dimension and might need large GPU memory. With the 64*64 tiles, you also need to create corresponding .txt file for the annotations (similar formatting of COWC dataset).

For training a new dataset, you always need a high-low resolution image pairs with ground truth bounding boxes for detection. Thank You.

**Comment by cl886699** [comment]
this also bother me a lot，in most detection task, we don't have the high resolution images. we can not downsample the original image, and then detect. it is more meaningful to contrast the detection result of original images to the detection result of super resolution images

**Comment by spacewalk01** [comment]
@cl886699 you are right, that is the drawback of super-resolution models. Most of them are trained on images down-sampled from high-resolution images which tend to learn downsampling patterns. So, they don't work on actual low-resolution images.
