### ISSUE TITLE
config_GAN.json ?

### ISSUE THREAD

**Issue by jinzhenmu** [Jakaria08/EESRGAN#8]
hi , when i use  python test.py -c config_GAN.json to test 

- error happens 

- EESRGAN/scripts_for_datasets/COWC_EESRGAN_FRCNN_dataset.py", line 32, in __getitem__
    img_path_gt = os.path.join(self.data_dir_gt, self.imgs_gt[idx])

- IndexError: list index out of range

- It is the  config_GAN.jon  problem?

**Comment by Jakaria08** [comment]
Duplicate of #7
