### ISSUE TITLE
python train.py -c config_GAN.json

### ISSUE THREAD

**Issue by huangxueyan** [Jakaria08/EESRGAN#9]
when i run python train.py -c config_GAN.json
I meet a problem: 
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3, 64, 3, 3]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

I surely changed all the Relu(inplace = False), but it doesnot work

**Comment by Jakaria08** [comment]
Sorry for the late reply. You should use torch==1.1.0 or torch==1.2. Otherwise, you might face this error.
